# Generated by Django 4.2.11 on 2024-05-14 05:47

from django.db import migrations

def custom_migration(apps,schema_editor):
    Books2 = apps.get_model('BookApp','Books2')
    Books = apps.get_model('BookApp','Books')
    
    for book in Books.objects.all():
        Books2.objects.create(
            title=book.title,
            genre=book.genre,
            price=book.price,
            published_date=book.published_date,
            author=book.author,
            publisher=book.publisher,
            
        )

class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_books2'),
    ]

    operations = [
        migrations.RunPython(custom_migration)
    ]
